### PR TITLE
Update to minecraft 1.10.2

### PR DESCRIPTION
**Pull request by Techcable**
It compiles and I've fixed all the crashes I could find.
I can connect to my localhost server and hypixel.

This is my first time programming in rust however, so I may have made some beginner mistakes.
Specifically I'm not proud of the fact that I had to insert a `block_entity.clone()` because I couldn't get borrowing the nbt to work properly.

### CODE REVIEW

**Comment by phase** [comment]
I'm surprised as such little changes were needed!

**Comment by ZombiePork** [comment]
How did you compile without errors in the first place? I'm still needing help rip

**Comment by bjorn3** [comment]
@ZomviePork Have you used rust nightly?

**Comment by Thinkofname** [comment]
Ideally the sign special case would be removed now but this works. Thanks

**Pull request merged**
